### ISSUE TITLE
라이센스가 어떻게 되나요??

### ISSUE THREAD

**Issue by silverstar0727** [corinthionia/corinthionia.github.io#2]
블로그가 너무 예쁜데 혹시 포크 떠서 써도 될까요...!

**Comment by corinthionia** [comment]
안녕하세요! 🙂🙂

현재 이 블로그는 제 개인용으로 제작한 거라 아직 수정해야 할 부분도 많고 하드코딩 된 부분도 많아서 아직은 불가능할 것 같습니다 🥲
조만간 개츠비 테마로 출시해 보려고 하고 있어서 빠른 시일 내로 완성해 보도록 하겠습니다! 😀😀

**Comment by silverstar0727** [comment]
ㅜㅜ 아쉽네요 답변 감사합니다!! 

완성되면 코멘트 한 번만 달아주실 수 있을까요 ㅎㅎ 너무 잘만드셔서 취향저격이네요

**Comment by corinthionia** [comment]
넵 좋게 봐 주셔서 너무 감사드립니다! ㅎㅎ
